<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Portfolio of Biaggi (GiGi) Barber and landing page for belleviSite Website Solutions">
  <meta name="keywords" content="Biaggi, Biaggi Barber, GiGi Barber, GiGi B., Biaggi B., website, web design, small business, cheap websites, cheap business website, resume website, wedding website, event website, portfolio website, website solutions, baltimore web design, baltimore website, baltimore websites, maryland web deisgn, maryland web developer, baltimore web developer, dc web developer, maryland web design, baltimore web design, dc web design, business web design, small business web design, restaurant web design, hair web design, portfolio, web design portfolio, website portfolio, restaurant website, restaurant web design, resume web design, event web design, wedding web design, restaurant web solution, resume web solution, event web solution, wedding web solution, restaurant web development, resume web development, event web development, wedding web development, freelance web developer, baltimore freelance web developer, dc freelance web developer, silver spring web developer, silver spring web design"> 
  <meta name="author" content="Biaggi 'GiGi' Barber">
 
 

  <title>belleviSite Website Solutions</title>

  <link rel="canonical" href="https://www.bellevisite.com">


  <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
<link rel="manifest" href="/images/favicon/site.webmanifest">
<link rel="mask-icon" href="/images/favicon/safari-pinned-tab.svg" color="#741ee8">
<link rel="shortcut icon" href="/images/favicon/favicon.ico">
<meta name="msapplication-TileColor" content="#272eff">
<meta name="msapplication-config" content="/images/favicon/browserconfig.xml">
<meta name="theme-color" content="#741EE8">

  <!-- Bootstrap 4 CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



<!-- Fonts -->
  <link rel="stylesheet" href="https://use.typekit.net/ziy4rhs.css">


<!-- Custom -->

<link rel="stylesheet" href="css/lightbox.min.css">

  <link href="css/style.css" rel="stylesheet">

  <script src="https://kit.fontawesome.com/e70f5a63c7.js" crossorigin="anonymous"></script>

  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
  {
    "@context" : "http://schema.org",
    "@type" : "Product",
    "name" : "visually appealing websites",
    "image" : "https://www.bellevisite.com/images/locavino.png",
    "description" : "Good websites should be “belles visites” for consumers, and I aim to provide website solutions that serve as those lovely visits.",
    "brand" : {
      "@type" : "Brand",
      "name" : "belleviSite",
      "logo" : "http://www.googleusercontent.com/images/bellevisite-logo.png"
    },
    "offers" : {
      "@type" : "Offer",
      "price" : "$200*"
    }
  }
  </script>
</head>

<body>

  <div class="d-flex" id="wrapper">

        <div class="container-fluid">


        <!--  Header -->
<header id="gigi-presents-bellevisite">
  <div class="container">
    <div class="row justify-content-center align-items-center mt-4">    
      <div col="col-12 col-md-6 offset-md-3">
        <div class="text-wrapper">
        <p>Welcome to</p>
<h1><span class="business-name"><span class="first-name">belle</span><span class="last-name">viSite</span></span></h1>


    <a class="enter" href="#bellevisite-main-nav"><img class="rounded img-fluid mx-auto d-block" src="images/enter.png"></a>

  </div>
</div>
</div>

</div>

</header>

<!-- Navbar -->

<div class="main-container">
<nav class="navbar navbar-expand-lg site_navbar site-navbar-light" id="bellevisite-main-nav">

          <a class="navbar-brand" href="index.html">                
            <img src="images/bellevisite-logo.png" alt="belleviSite logo with name in violet and blue cursive next to a violet laptop icon framing a blue heart in a white closing html tag" width="175" height="45">
          </a>
          <div class="toggler-right">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#site-nav">
                <span class="fas fa-bars"></span> Menu
              </button>
            </div>

          <div class="collapse navbar-collapse" id="site-nav">
            <ul class="nav navbar-nav ml-auto">
           
             
  <li class="nav-item text-center">
    
                          <a class="nav-link text-center" href="index.html#bellevisite-barber-profile"> 
                                <i class="icon fas fa-id-card"></i>
                          <p class="mx-auto hidden-text">Profile</p>
                        </a>
                      </li>
                  
                     
                  
                          <li class="nav-item text-center">
                          <a class="nav-link text-center" href="index.html#barber-portfolio-projects"> 
                              <i class="icon fas fa-folder-open"></i>                              
                              <p class="mx-auto hidden-text">Projects</p>
                              </a>
                              </li>

                              <li class="nav-item text-center">
                                  <a href="intake-form.html" class="nav-link text-center"> 
                                      <i class="icon fas fa-check-circle"></i>
                                       <p class="mx-auto hidden-text">Intake Form</p>
        
                                      </a>
                                      </li>

                                      <li class="nav-item text-center">
                                        <a href="services.html" class="nav-link text-center"> 
                                          <i class="icon fas fa-concierge-bell"></i>
                                         <p class="mx-auto hidden-text">Other Services</p>
              
                                            </a>
                                            </li>

                         <li class="nav-item text-center">
                          <a href="index.html#bellevisite-contact-gigi" class="nav-link text-center"> 
                                <i class="icon fas fa-paper-plane"></i>
                              <p class="mx-auto hidden-text">Contact</p>

                              </a>
                              </li>

                            

   </ul>
  </div>

                </nav>



 <!-- Page Content -->
 <div class="page-content-wrapper">


            
        <!-- First Section -->
          

      <!-- End Section -->

      <!-- BelleviSite Intro Article -->

        <article id="about-bellevisite" class="site-section no-padding">
          <div class="container-bg">
           <div class="row mt-5">
                <div class="col-md-6">
                    <div class="article-container mt-2">                   
                    <!-- <p> Even further than that, a user’s website experience influences overall customer satisfaction and/or public perception. I therefore conceived of the professional name <span class="business-name"><span class="first-name">belle</span><span class="last-name">viSite</span></span> (pronounced here “bell visit“) to demonstrate my guiding mission.</p>                   -->
                <p>“Une belle visite” in French <a href="https://www.linguee.fr/francais-anglais/traduction/une+belle+visite.html">translates</a> as “a lovely visit,” or literally-speaking as “a beautiful visit.” An online presence is often crucial for organizations, and so the name <span class="business-name text"><span class="first-name">belle</span><span class="last-name">viSite</span></span> (pronounced here “bell visit“) conveys my mission to create websites that will leave users pleased and satisfied with their experience. Good websites should be “belles visites” for consumers, and I aim to provide website solutions that serve as those lovely visits. <i>My technical capabilities include:</i></p>
                
                </div>
               
             
              </div>
              <div class="col-md-6">
                  <div class="chip-container">

                  <div class="mdc-chip-set">

                      <button class="mdc-chip">
                        <span class="mdc-chip__text">HTML5</span>
                      </button>
                      <button class="mdc-chip">
                            <span class="mdc-chip__text">jQuery (JavaScript)</span>
                          </button>
                          <button class="mdc-chip">
                                <span class="mdc-chip__text">CSS3</span>
                              </button>
                              <button class="mdc-chip">
                                    <span class="mdc-chip__text">Wordpress*</span>
                                  </button>
                                  <br>
                                  <button class="mdc-chip">
                                        <span class="mdc-chip__text">Bootstrap 4</span>
                                      </button>
                                      <button class="mdc-chip">
                                            <span class="mdc-chip__text">Hypertext Access Configuration</span>
                                          </button>
                                          <button class="mdc-chip">
                                                <span class="mdc-chip__text">Search Engine Optimization (SEO)</span>
                                              </button>
                                              <button class="mdc-chip">
                                                    <span class="mdc-chip__text">e-Commerce Integration*</span>
                                                  </button>
                                                  <button class="mdc-chip">
                                                      <span class="mdc-chip__text">Website Performance Optimization</span>
                                                    </button>
                                                    
                    </div>
                    <div class="mt-2">
                 <p>

                    <small class="capabilities-note">*Please note that these components will require third-party software or component purchases.</small>
                  </p>
                </div>
              </div>

                </div>

                <!-- <div class="about-img-frame mt-3">
                  <div class="about-img">
                      <span role="img" aria-label="laptop displaying the belleviSite logo, an HTML closing tag with a blue heart."></span>
                  </div>
                </div> -->
              </div>
            </div>
           

            
         
   


        </article>

   
        <section id="bellevisite-barber-profile" class="site-section">
          <div class="container py-3">
            <div class="card" id="gigi-profile-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
              <div class="row d-flex no-gutters align-items-left justify-content-left text-left">
                <div class="col-md-4">
                  <div class="card-img-body">
                </div>
                </div>                 

                  <div class="col-md-8 px-3">
                    <div class="wrapper">                                                                       

                    <div class="card-block px-3">
                      <h3 class="card-title"><span class="business-name"><span class="first-name">biaggi</span><span class="last-name">Barber</span></span></h3>
                      <h6 class="text-muted"><span class="icon fas fa-briefcase profile-icon mb-1 mr-1"></span>  Junior Web Developer/Designer</h6>
                      <h6 class="text-muted"><span class="icon fas fa-map-marker-alt profile-icon mb-1 mr-1"></span>  Washington D.C./Baltimore Metropolitan Area</h6>
                      <p class="card-text">I am passionate about creating visually appealing websites for a variety of screen sizes using front-end tools such as HTML5, CSS3,  jQuery (a JavaScript library), Bootstrap 4, and Wordpress.</p>                


                    <div class="row mb-2">
                      <div class="col-md-12">
                          <div class="dev-skills">
                              <div class="container" style="display:inline-block !important; margin-left:auto !important; margin-right:auto !important; vertical-align: middle !important;">
                        
                                <div class="row mb-1">
                          <div class="col-md-1 col-sm-2 col-2">
                            <div class="dev-tools" style="width: 100%;">
                                <i class="fab fa-html5 dev-tools-icon ml-3"></i>
                            </div>
                          </div>
                
                            <div class="col-md-11 col-sm-10 col-10">
                
                                <div class="progress ml-1" style="height: 10px; width:90% !important; margin-top: 1% !important;">
                                    <div class="progress-bar" role="progressbar" style="width: 90%;" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">90%</div>
                                </div>
                          </div>
                
                          </div>
                
                          <div class="row mb-1">
                            
                              <div class="col-md-1 col-sm-2 col-2">
                                  <div class="dev-tools">
                
                                      <i class="fab fa-css3-alt dev-tools-icon ml-3"></i> 
                                    </div>
                              </div>
                
                    
                                <div class="col-md-11 col-sm-10 col-10">
                                  <div class="progress ml-1" style="height: 10px; width:90% !important; margin-top: 1% !important;">
                                    <div class="progress-bar" role="progressbar" style="width: 90%;" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">90%</div>
                                    </div>
                                </div>
                                
                              </div>
                
                              <div class="row mb-1">
                            
                                  <div class="col-md-1 col-sm-2 col-2">
                                      <div class="dev-tools">
                
                                          <i class="fab fa-js dev-tools-icon ml-3"></i>
                                        </div>
                                  </div>
                
                        
                                    <div class="col-md-11 col-sm-10 col-10">
                                      <div class="progress ml-1" style="height: 10px; width:90% !important; margin-top: 1% !important;">
                                        <div class="progress-bar" role="progressbar" style="width: 70%;" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100">70%</div>
                                        </div>
                                    </div>
                                    
                                  </div>
                
                                  <div class="row mb-1">
                            
                                      <div class="col-md-1 col-sm-2 col-2">
                                          <div class="dev-tools">
                
                                              <i class="fab fa-bootstrap dev-tools-icon ml-3"></i>
                                            </div>
                                      </div>
                
                            
                                        <div class="col-md-11 col-sm-10 col-10">
                                          <div class="progress ml-1" style="height: 10px; width:90% !important; margin-top: 1% !important;">
                                            <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100">80%</div>
                                            </div>
                                        </div>
                                        
                                      </div>
                
                                      <div class="row mb-1">
                            
                                          <div class="col-md-1 col-sm-2 col-2">
                                              <div class="dev-tools">
                
                                                  <i class="fab fa-wordpress dev-tools-icon ml-3"></i>
                                                </div>
                                          </div>
                
                                
                                            <div class="col-md-11 col-sm-10 col-10">
                                              <div class="progress ml-1" style="height: 10px; width:90% !important; margin-top: 1% !important;">
                                                <div class="progress-bar" role="progressbar" style="width: 70%;" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100">70%</div>
                                                </div>
                                            </div>
                                          </div>
    
    
                                        </div>
                                        </div>

                                      </div>

                  </div>
        
                </div>
              </div>
            </div>
          </div>
        </section>

                




          <section id="barber-portfolio-projects" class="site-section">
             
  <div class="container justify-items-center">

    


        <div class="row row-no-gutters">
            <div class="site-animate fadeInUp site-animated col-md-4 no-padding">
              <div class="container no-padding mb-4">
                  <div class="project-image-wrapper">

                  <a href="https://www.bellevisite.com/images/locavino.png" data-lightbox="gallery" class="gallery-lightbox-1 site-thumbnail image-popup">
                    <img id="locavino-project" src="https://www.bellevisite.com/images/locavino.png" alt="Locavino website on laptop, desktop tablet, and phone screens" class="img-fluid lazyload">
                  </a>
              
            </div>
            <div class="container project-text no-padding">
                <h4 class="project-title text-center">Local Restaurant</h4>
                <div class="transparent-text-bg text-center">
<p>Developed and designed this website for a local wine café using HTML5, CSS3, and jQuery (JavaScript), including JavaScript functions I created personally.
  </p>                
  <a class="btn btn-primary" href="https://bibar7.github.io/Locavino/">View Now</a>
              </div>
            </div>
        </div>
      </div>

          <div class="col-md-4 no-padding">
            <div class="container no-padding mb-4">
              <div class="project-image-wrapper">
                <a href="https://www.bellevisite.com/images/reunion.png" data-lightbox="gallery" class="gallery-lightbox-2 site-thumbnail image-popup">
                      <img id="reunion-project" src="https://www.bellevisite.com/images/reunion.png" alt="Locavino website on laptop, desktop tablet, and phone screens" class="img-hover img-fluid lazyload">
                    </a>
                
            
          </div>
          <div class="container project-text no-padding">
              <h4 class="project-title text-center">Family Reunion Website</h4>
              <div class="transparent-text-bg text-center">
<p>Created a virtual home-base for my annual family reunion using HTML5, CSS3, jQuery, and JavaScript plugins among other tools.
  </p>                  
  <a class="btn btn-primary" href="https://bibar7.github.io/Barber-Bolling/">View Now</a>
            </div>
          </div>
        </div>
      </div>



      <div class="col-md-4 no-padding">
        <div class="container no-padding mb-4">
          <div class="project-image-wrapper">
             <a href="https://www.bellevisite.com/images/resume.png" data-lightbox="gallery" class="gallery-lightbox-3 site-thumbnail image-popup">
                  <img id="resume-project" src="https://www.bellevisite.com/images/resume.png" alt="Locavino website on laptop, desktop tablet, and phone screens" class="img-hover img-fluid lazyload">
                </a>
          
          
        </div>
        <div class="container project-text no-padding">
            <h4 class="project-title text-center">Curriculum Vitae</h4>
            <div class="transparent-text-bg text-center">
            <p>Extensively designed, customized, and coded (HTML, CSS, PHP, and JS) a basic resume template to showcases my career history and background.</p>
            <a class="btn btn-primary" href="https://bibar7.github.io/resume/">View Now</a>
          </div>
        </div>
    </div>
  </div>

</div>

      </div>

      <script>
        lightbox.option({
          'alwaysShowNavOnTouchDevices': true,
          'wrapAround': true,
        });
        $('.myLightbox').lightbox.option;


    </script>

            </section>


            


            <section id="call-to-action">

                <div class="row text-center justify-content-center align-items-center mb-5">
                    <div class="col-12">
                        <div class="container">
                          <p class="appeal-to-consumer">
                            Small businesses, restaurants, resumés, artist portfolios, music showcases, event homepages, freelance services… <br><span class="business-name"><span class="first-name">belle</span><span class="last-name">viSite</span></span> has the website solution to fit any need. Pricing starts as low as $200*!

                          </p>

<p class="call-to-action mt-4 mb-5">

                           Interested in commissioning a <span class="business-name"><span class="first-name">belle</span><span class="last-name">viSite</span></span> website solution? 
  <br>Click below to fill out the needs analysis questionnaire and get your customized quote.


</p>
                      
                        <a href="intake-form.html" class="btn btn-2 btn-primary">Get A Quote Today</a>
                      
                      </div>

                      <div class="container mt-5">
                        <small>
                          *pricing is dependent upon the complexity of your project, including the number of sub-pages required as well as media and third-party component integration. Please note that the client is responsible for costs such as domain hosting, brand/customized fonts, templates, stock images, etc. However, don't fret! I work closely with clients to select the best options for both your website and your wallet.
                        </small>
                      </div>
                      
                    </div>
                  </div>
                </section>




      
           
                    
      
      <section id="bellevisite-contact-gigi" class="site-section">


              

                      <div class="business-card container no-padding" id="bc-card">
                          <div class="bc-content align-items-center mt-2">

                              <div class="flex-row row-no-gutters d-flex justify-content-center">

                                  <div class="logo">
                        <img class="img-fluid" src="images/bellevisite-logo-icon.png">
                                  </div>

                            </div>

                            <div class="row row-no-gutters">
                                <div class="col-12">
                              <h3 class="name">Biaggi Barber</h3>
                            </div>
                            </div>

                            <div class="row row-no-gutters">
                                <div class="col-12">

                            <h5 class="job-title">Website Developer</h5>
                          </div>
                        </div>


                            <div class="flex-row row-no-gutters d-flex justify-content-center">
                                <div class="container bc-contact mb-1">


      <table class="table-borderless text-center">
        <tbody>
          <tr>
            <td>
              <a href="mailto:biaggi@bellevisite.com?Subject=Portfolio%20Contact%20via%20BC">biaggi@bellevisite.com</a>

            </td>
            <td>
              <i class="fas fa-heart align-middle bc-heart"></i>
            </td>
            <td>
              <a href="https://www.bellevisite.com/">www.bellevisite.com</a>

            </td>
            <td>
              <i class="fas fa-heart align-middle bc-heart"></i>
            </td>
            <td>
              <a href="tel:240-600-1289">(240) 600-1289</a>

            </td>

          </tr>
</tbody>




      </table>


    </div>

    </div>


  </div>



                      
              
              </section>

       


                    <!-- End Section -->

                  </div>

                  <!-- /#page-content-wrapper -->
<!-- Footer -->
                    <footer class="site-footer" id="bellevisite-page-footer">
                        <div class="container">
        
                                <div class="row">
                                  <div class="col-md-3 site-animate fadeInUp site-animated">
                                    <div class="container">
                                    <h4 class="mt-3 site-heading-2 footer-heading">About Me</h4>
                    
                                    <p class="mb-4" style="color: white;"> Biaggi “GiGi” Barber is a DC-native with a passion for mobile and personal computer-based technology. Check out her social media for more of her diverse interests!</p>
                                    <ul class="site-footer-social d-flex list-unstyled align-items-center justify-content-center text-center mt-2">
                                            <li class="site-animate fadeInUp site-animated"><a class="follow mr-4" href="https://github.com/bibar7" target="_blank" rel="noopener"><span class="soc-ico fab fa-github"></span></a></li>
                                            <li class="site-animate fadeInUp site-animated"><a class="follow mr-4" href="https://twitter.com/unefemmegigi" target="_blank" rel="noopener"><span class="soc-ico fab fa-twitter"></span></a></li>
                                            <li class="site-animate fadeInUp site-animated"><a class="follow mr-4" href="https://www.facebook.com/BelleviSite-105585511023935/" target="_blank" rel="noopener"><span class="soc-ico fab fa-facebook"></span></a></li>
                                        </ul>
                                  </div>
                                </div>
                                <div class="col-md-3 site-animate">
                                  <div class="container">
                                    <h4 class="mt-3 site-heading-2 footer-heading">Contact</h4>
                                    <ul class="footer-list list-unstyled">
                                      <li><a href="mailto:biaggi@bellevisite.com?Subject=Portfolio%20Contact%20via%20BC" class="no-padding mb-2 footer-site-link py-2 d-block">biaggi@bellevisite.com</a></li>                                     
                                        <li><a href="tel:240-600-1289" class="no-padding mb-2 footer-site-link py-2 d-block">(240) 600-1289</a></li>
                                        <li><a href="https://github.com/bibar7" class="no-padding footer-site-link py-2 d-block">GiGi's GitHub</a></li>
                                      </ul> 
                                  </div>
                                </div>
                                  <div class="col-md-3 site-animate fadeInUp site-animated">
                                    <div class="container">
                                    <div class="site-footer-widget mb-4 fadeInUp site-animated">
                                        <h4 class="mt-3 site-heading-2 footer-heading">More belleviSite</h4>
                                        <ul class="footer-list list-unstyled">
                                            <li><a href="intake-form.html" class="no-padding mb-2 footer-site-link py-2 d-block">Intake Assessment</a></li>
                                            <li><a href="services.html" class="no-padding mb-2 footer-site-link py-2 d-block">Other IT Services</a></li>
                                            <li><a href="cv/Barber-2020-Resume.pdf" class="no-padding mb-2 footer-site-link py-2 d-block">Download Resume</a></li>                      
                   
                                          </ul>
                                    </div>
                                  </div>
                                </div>
                              
                                  <div class="col-md-3 site-animate text-center justify-contents-center">
                                    <div class="container">
                                        <a href="index.html" class="mb-1">                
                                            <img class="mt-3 img-fluid lazyload" src="images/logo-vertical.png" alt="bellevisite icon over company name">
                                            </a>                    
                                       
                    
                    
                    
                                </div>
                              </div>
                    
                              </div>
                    
                            </div>
                             
                           
                    </footer>


                    <!-- End Footer -->
    
          </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
     <script src="vendor/jquery/jquery.easing.1.3.js"></script>
     <script src="vendor/jquery/jquery.waypoints.min.js"></script>
     <script src="vendor/jquery/lightbox.js"></script>


  <!-- Menu Toggle Script -->
  <!-- <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#site-nav").toggleClass("toggled");
    });
 
  </script> -->

</body>

</html>
